### PR TITLE
Remapped VCF to build 38, script added

### PR DESCRIPTION
**Pull request by g-pyxl**
Added small script to liftover VCF from hg19 to hg38.

- - -
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/validation/3)

### CODE REVIEW

**Review by natashapinto — CHANGES_REQUESTED** [review]
> Reviewed 4 of 4 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3)* status: all files reviewed, 1 unresolved discussion (waiting on @g-pyxl)

___
*[`validation/super_sample/remap.py` line 39 at r1](https://reviewable.io/reviews/moka-guys/validation/3#-NwEJydsEA2mlIGo3fcE:-NwEJydsEA2mlIGo3fcF:bwxut7t) ([raw file](https://github.com/moka-guys/validation/blob/284e3cd6a1081d91b0a880a7d4fae163f78d6588/validation/super_sample/remap.py#L39)):*
> ```Python
>     # Iterate over each variant in the input VCF
>     for record in input_vcf:
>         print(record) # debugging
> ```

print statement still needed?

**Comment by g-pyxl** [comment]
Debug print removed, pushed.

**Review by natashapinto — COMMENTED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3)* status: all files reviewed, 1 unresolved discussion (waiting on @g-pyxl)

**Review by natashapinto — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3#-:-NwJMr2P5MtSagnsWgw_:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @g-pyxl)

**Review by g-pyxl — COMMENTED** [review]
> Reviewed 3 of 4 files at r1, 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3)* status: all files reviewed, 1 unresolved discussion (waiting on @g-pyxl)

**Review by g-pyxl — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3#-:-NwJQO-a3pwSgaQSUDwX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @natashapinto)

___
*[`validation/super_sample/remap.py` line 39 at r1](https://reviewable.io/reviews/moka-guys/validation/3#-NwEJydsEA2mlIGo3fcE:-NwJQIlr3Wb2he8G-mV_:b-896fix) ([raw file](https://github.com/moka-guys/validation/blob/284e3cd6a1081d91b0a880a7d4fae163f78d6588/validation/super_sample/remap.py#L39)):*
<details><summary><i>Previously, natashapinto (Natasha Pinto) wrote…</i></summary><blockquote>

print statement still needed?
</blockquote></details>

Done.

**Review by natashapinto — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/validation/3)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @g-pyxl)

**Pull request merged**
